apiVersion: v1
kind: Service
metadata:
  name: q1-service
  namespace: q1
  labels:
    app: q1-service
spec:
  selector:
    app: q1-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  clusterIP: None